version: "3"
services:
  scout-sql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_USER: boi
      MYSQL_PASSWORD: userpassword
      MYSQL_DATABASE: scout
  scout-mongo:
    image: bitnami/mongodb
    restart: always
    ports:
      - "27017:27017"
    environment:
      - MONGODB_USERNAME=boi2
      - MONGODB_PASSWORD=password123
      - MONGODB_DATABASE=scout
